name: Craft4Plus
version: 0.4
main: com.craft4plus.main.Main
authors: [chrismin13, UnitedGamersMC, Vadyn]
commands:
    ranks:
        description: Use this command with any rank name after it and a player name to get that player on that rank. Checks if player is in any other ranks before proceeding.
        usage: /ranks <rankname> <playername>
    wp:
        description: Warp to a different location.
        usage: /wp
    setwp:
        description: Set a warp in a specific location.
        usage: /setwp
    parkourreset:
        description: Get back to the beggining of the parkour.
        usage: /parkourreset
    builds:
        description: Custom command for the Builders!
        usage: /builds <args>
    qc:
        description: Custom command for QuestCraft
        usage: /qc <args>
    customgive:
        description: Get Custom Items
        usage: /customgive <id>
depend: [Vault]
